### ISSUE TITLE
Application setup

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#1]
Need to initialize an Angular application with project name 'viz-demo-ng`.  This will be used to test various visualization technologies to evaluate whether to use in applications.

* add `.gitignore` for Angular project
* add `.gitattributes` similar to other repos

The application design needs a way to select visualizations.  I recommend adding menus but if that is difficult then do buttons.  See attached image.  If using menus there would be a menu for the technology and under that sub-menus for each demo.  For example `1 Day TS Line Graph` would display one day-interval time series using a line graph.

![angular-test-app](https://user-images.githubusercontent.com/6448274/83444943-62f36280-a409-11ea-9dbb-ee654b506bc4.jpg)

Each graph would use a TSTool json file for configuration and have test data of the json file and time series data (CSV or other).  Start with the example data I previously emailed and I'll provide more examples.  I recommend that these go into a folder under assets called `app/data-ts`, which is what we are using for the InfoMapper.  We are considering `assets/app` to the the "root" folder for the application's assets.

**Comment by smalers** [comment]
The `.gitignore` file still needs to be filled out.  Typically it has files for Angular development environment.  See the InfoMapper and SNODAS tools for an example.

**Comment by gsofia23** [comment]
General application is set up, and designed in a way to select various visualizations. +  .gitignore and .gitattributes added and filled
