### ISSUE TITLE
Feedback on Home

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#11]
Here are some comments on the `Home` page.

Change to the following content.

"This site is an [Open Water Foundation](https://openwaterfoundation.org/) Angular application that demonstrates visualizations for time series and other data.  Specific examples use popular and feature-rich libraries such as ChartJS and Plotly.  Examples focus on water-related data.  The demonstrations are used to prototype and troubleshoot features that are integrated into other Angular applications.

See the Open Water Foundation [owf-app-viz-demo-ng](https://github.com/OpenWaterFoundation/owf-app-viz-demo-ng) repository for more information.

**Comment by smalers** [comment]
Can this text be shown in the main window area at all times?  The graphs are popups so hopefully they can pop up on top of this text?

**Comment by gsofia23** [comment]
Home page text displayed in main window for each demo.
