### ISSUE TITLE
Plotly examples feedback

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#17]
Plotly is now the default in InfoMapper and there will be increased focus on Plotly as we go forward, in particular to achieve results similar to TSTool and handle graph configurations from TSTool.  Below are comments on the current plotly examples:

1. Change first menu to ***Basic Example:  Month, Line*** and URL to `/plotly/basic-month-line`.
2. Change second menu to ***SNODAS:  Day, Line*** and URL to `/plotly/snodas-day-line`.
3. Move this to the end.  If possible, add a separator in the menu so that all heatmap examples can be grouped.  Change the menu to ***Basic Heatmap***.  I will add a separate issue for an example for time series, but this is a lower priority until other cleanup is done.  Change the URL to `/plotly/basic-heatmap`.
4. Change fourth menu to ***TSTool Graph:  Month, Line** and the URL to `/plotly/tstool-month-line`.  Get rid of the extra popup dialog that says `0300911 Total Diversion`.  I assume that was for troubleshooting.

**Comment by gsofia23** [comment]
URL paths updated for each Plotly demo example. Basic Heatmap moved to the bottom of demo menu list.

**Comment by gsofia23** [comment]
Still looking into reason for extra popup. Similar problem appears in only one other example

**Comment by gsofia23** [comment]
Incorporated an additional heatmap example from original owf heatmap repo. Uses daily streamflow data acquired from csv format

**Comment by smalers** [comment]
Please change the labels similar to what I suggested.  The word "Demo" is redundant in all menus and can be removed.  The entire application is a demonstration.   I also want the menus to indicate the type of graph because we are going to add more examples over time for different char types.

Similarly, "demo" can be removed from URLs since it is redundant.  As much as possible, the user experience should be efficient.

The additional popup is still happening.   I am opening as a separate issue so that when the menu/URL name changes are made we can close this issue.

**Comment by gsofia23** [comment]
"demo" redundancies omitted
