### ISSUE TITLE
The menus need to clearly indicate the data and demo content

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#2]
The main menus should be for charting packages, as already started.  The sub-menus should be specific demonstrations that when clicked, show the visualization.

Users of the demo application, like me, don't know what is behind the menus.  Therefore the menus need to be specific, for example:

* ***Day time series, line graph***
* ***Month time series, point graph***
* ***Day and Month time series, bar and line graph***
* ***Heatmap, day time series***

The time series interval and the type of visualization are two key characteristics but there might be others.  The menus should match across charting packages so it is easy to compare graphs.  Examples should be added when something different needs to be demonstrated, not just to fill out every possible combination.  Use separators if necessary to group examples, for example, group by time series data interval or by chart type.  Note that we will likely not focus much on pie charts, etc. but we might have some examples like that in the future.  Over time we will probably have many small dataset examples but it is also important to have some large dataset examples (like in the separate "viz" repositories so that we know a charting package will work for large time series.

**Comment by smalers** [comment]
The comments in other issues provide more specific wording.  Close this issue once those are completed.

**Comment by gsofia23** [comment]
Specific menu naming conventions completed.
