### ISSUE TITLE
Showdown Options example images are not displayed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#23]
The ***Showdown Options*** example images are not displaying.  This needs to be fixed.  I did change the image in the original to a photo that I took so that no attribution to a third party is needed.  See in the [Poudre Basin Information](http://poudre.openwaterfoundation.org/latest/#/map/entities-trails) website (show the info for the Poudre Trails layer).

**Comment by gsofia23** [comment]
Image path fixed and displaying properly
