### ISSUE TITLE
Add documentation for each charting package

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#4]
The application needs basic documentation for each charting package.  Rather than putting this in the menu and hen have to press on a button to get the chart, I recommend that the documentation is provided in one or two ways:

1. Add a section in the main `README.md` for each package.
2. If it helps to explain, make the first menu under a package be `Documentation` and then include what you have done already for the Plotly example.

Some developers are going to want to read the `README.md` without setting up the application so it may make sense to put similar documentation in both places.

**Comment by smalers** [comment]
Also, add links to the other repos for charting packages.  Focus on Angular integration in the README(s) for this repository.

**Comment by gsofia23** [comment]
Charting package descriptions and respected OWF repo links added to main README as well as  located in resource tab.

Closing this issue

**Comment by gsofia23** [comment]
Charting package descriptions and respected OWF repo links added to main README as well as located in resource tab.

Closing this issue
