### ISSUE TITLE
Add an application configuration file similar to InfoMapper

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#8]
The application needs an top-level asset json file for configuration.  What we have implemented for InfoMapper works well.  Talk to Josh about how it was done.

Once implemented, we can hopefully add more menus.  The menus in the configuration can then match folders in assets for data.

Also, use folders in assets for libraries so as to not clutter up the main assets folder.  InfoMapper does a good job of organization.

**Comment by gsofia23** [comment]
TSTool configuration graphs implemented along with matching file structure - use of ``assets/app`` folder for top-level json configuration fies
