### ISSUE TITLE
Change Links menu to Resources

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-viz-demo-ng#9]
I recommend the following changes:

1. Rename the ***Links*** menu to ***Resources***.
2. For each charting package, add the link to the corresponding OWF repository.
3. Replace `at the moment` with `focus on popular and feature-rich charting libraries. that are used in OWF applications`.
4. Consider converting the content of the page to Markdown and use with HashLocationStrategy.

**Comment by gsofia23** [comment]
Updated tab name to 'Resources'. Charting packages link to corresponding OWF repository. Content converted to use Markdown and ShowdownJS.
